### ISSUE TITLE
Document Epson LX-350 destruction procedure Document Epson LX-350 destruction procedure

### ISSUE THREAD

**Issue by inickles** [oxidecomputer/offline-keystore#132]
This may be more of an issue for RFD than 369 than this repo, but I'm putting it here for now, which will be used to tracking purposes.

**Comment by inickles** [comment]
I'm happy to close and move elsewhere if we have another spot in mind,

**Comment by kc8apf** [comment]
Completed in https://rfd.shared.oxide.computer/rfd/369#_act_7_printer_destruction
