### ISSUE TITLE
Support for signing RoT debug credentials

### ISSUE THREAD

**Issue by mx-shift** [oxidecomputer/offline-keystore#142]
RFD 333 outlines how NXP LPC55 debug authentication will be used to allow in-field debugging of production RoT devices.  Part of that model involves a debug credential being signed by one of the RoT roots set in the device's CMPA.  Since the private keys for those roots are stored in offline keystores (see RFD286), `oks` will need to be extended to perform the same signing operation done by `lpc55_sign debug-credential`.

**Comment by kc8apf** [comment]
Performing the signing is fairly straightforward but what about the audit trail.  `oks ca` currently calls into `openssl ca` which handles serial numbers and creating a log but `openssl ca` will only generate x509 certs.  Do we create a parallel set of state for a new `oks debug-cred`?

**Comment by flihp** [comment]
This has largely been solved, all but the audit question. I'm closing this issue and will be creating a separate one for answering questions w/r/t the audit trail.
